openapi: 3.0.0
info:
  description: "Simex Drop-Off API"
  version: 1.0.0
  title: SIMEX Drop-Off API
tags:
  - name: healthcheck
    description: Healthcheck API
  - name: dropoff
    description: Drop-Off Service endpoint

paths:
  /:
    get:
      tags:
        - healthcheck
      x-jvm-package: healthcheck
      summary: healthcheck
      description: healthcheck endpoint
      operationId: healthcheck
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"

components:
  schemas:
    HealthResponse:
      type: object
      properties:
        serviceStatus:
          type: string
          enum: [ OK, BROKEN ]
      required:
        - serviceStatus
