openapi: 3.0.0
info:
  description: "Simex Drop-Off API"
  version: 1.0.0
  title: SIMEX Drop-Off API
tags:
  - name: healthcheck
    description: Healthcheck API
  - name: dropoff
    description: Drop-Off Service endpoint

paths:
  /:
    get:
      tags:
        - healthcheck
      x-jvm-package: healthcheck
      summary: healthcheck
      description: healthcheck endpoint
      operationId: healthcheck
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
  /drop-off:
    post:
      tags:
        - dropOff
      x-jvm-package: dropoff
      summary: Drop off endpoint
      description: Drop off endpoint for all requests
      operationId: dropOffRequest
      requestBody:
        description: a SIMEX message
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SimexMessage'
      responses:
        '204':
          description: Ok
        '400':
          description: bad request
        '503':
          description: there is a problem handling this request - something is not available


components:
  schemas:
    HealthResponse:
      type: object
      properties:
        serviceStatus:
          type: string
          enum: [ OK, BROKEN ]
      required:
        - serviceStatus

    SimexMessage:
      type: object
      properties:
        endpoint:
          $ref: '#/components/schemas/EndPoint'
        client:
          $ref: '#/components/schemas/Client'
        originator:
          $ref: '#/components/schemas/Originator'
        data:
          type: array
          items:
            $ref: '#/components/schemas/Datum'
      required:
        - endpoint
        - client
        - originator
        - data

    EndPoint:
      type: object
      properties:
        resource:
          type: string
          description: the endpoint resource
        method:
          type: string
          description: the call type
        entity:
          type: string
          description: optional business entity
      required:
        - resource
        - method

    Client:
      type: object
      properties:
        clientId:
          type: string
          description: the client identifying string
        requestId:
          type: string
          description: the request id
        sourceEndpoint:
          type: string
          description: the client's endpoint from with the call was made
        authorization:
          type: string
          description: the authentication/authorization token
      required:
        - clientId
        - requestId
        - sourceEndpoint
        - authorization

    Originator:
      type: object
      properties:
        clientId:
          type: string
          description: the client ID of the originator that started the COE
        requestId:
          type: string
          description: the request Id of the originator that started the COE
        sourceEndpoint:
          type: string
          description: the endpoint of the originator that started this COE
        originalToken:
          type: string
          description: security token used to make the request
        security:
          type: string
          description: the client-defined security level to apply
        messageTTL:
          type: integer
          format: int64
          description: the optional setting for message TTL
      required:
        - clientId
        - requestId
        - sourceEndpoint
        - originalToken
        - security

    Datum:
      type: object
      properties:
        field:
          type: string
          description: the name of the field
        value:
          type: string
          description: the value to evaluate
        check:
          type: string
          description: the check or type of operation for the evaluation
      required:
        - field
        - value

